import "./vitest.js";
import { createServer } from "node:http";
import { registry } from "@hookkit-dev/core";
import { afterAll, describe, expect, it } from "vitest";
import { hookkit } from "./index.js";

const secret = "whsec_sdk_test_secret";

// Minimal loopback receiver that verifies Stripe signatures with core's
// verifier — exercises sendTo over HTTP without any external network.
const received: { rawBody: Buffer; headers: Record<string, string> }[] = [];
const server = createServer((req, res) => {
	const chunks: Buffer[] = [];
	req.on("data", (chunk) => chunks.push(chunk));
	req.on("end", () => {
		const rawBody = Buffer.concat(chunks);
		const headers = Object.fromEntries(
			Object.entries(req.headers).map(([key, value]) => [key, String(value)]),
		);
		received.push({ rawBody, headers });
		const result = registry.get("stripe").verify({ rawBody, headers, secret });
		res.statusCode = result.valid ? 200 : 400;
		res.end(JSON.stringify(result));
	});
});
await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
const address = server.address();
const url = `http://127.0.0.1:${typeof address === "object" && address ? address.port : 0}/webhooks/stripe`;

afterAll(() => new Promise<void>((resolve) => server.close(() => resolve())));

describe("sdk builder", () => {
	it("delivers a valid event that the receiver accepts", async () => {
		const stripe = hookkit.stripe({ secret });
		const res = await stripe.event("checkout.session.completed").sendTo(url);
		expect(res).toBeAccepted();
		expect(res.ms).toBeGreaterThanOrEqual(0);
	});

	it("delivers the exact generated bytes", async () => {
		const stripe = hookkit.stripe({ secret });
		const evt = stripe.event("checkout.session.completed").build();
		received.length = 0;
		await stripe.event("checkout.session.completed").sendTo(url);
		expect(received[0]?.rawBody.equals(evt.rawBody)).toBe(true);
	});

	it("tamperSignature() forces a 400 rejection", async () => {
		const stripe = hookkit.stripe({ secret });
		const res = await stripe
			.event("checkout.session.completed")
			.tamperSignature()
			.sendTo(url);
		expect(res).toHaveRejectedWithStatus(400);
	});

	it("withTimestamp() pins the signing timestamp", () => {
		const stripe = hookkit.stripe({ secret });
		const evt = stripe
			.event("checkout.session.completed")
			.withTimestamp(1710000000)
			.build();
		expect(evt.headers["Stripe-Signature"]).toContain("t=1710000000");
	});

	it("applies overrides through the builder", () => {
		const stripe = hookkit.stripe({ secret });
		const evt = stripe
			.event("checkout.session.completed", {
				overrides: { data: { object: { amount_total: 777 } } },
			})
			.build();
		const parsed = evt.parsed as { data: { object: { amount_total: number } } };
		expect(parsed.data.object.amount_total).toBe(777);
	});

	it("rejects unknown providers eagerly", () => {
		expect(() => hookkit.provider("not-a-provider", { secret })).toThrow(
			/Unknown provider/,
		);
	});
});
